# Generated by Django 5.0.1 on 2024-01-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='ruling_house_one',
            new_name='ruling_planet_one',
        ),
        migrations.RenameField(
            model_name='components',
            old_name='ruling_house_two',
            new_name='ruling_planet_two',
        ),
    ]
