# Generated by Django 5.0.1 on 2024-01-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_rename_ruling_house_one_components_ruling_planet_one_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrengthWeakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strength", models.TextField()),
                ("weakness", models.TextField()),
                (
                    "zodiac_sign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.zodiacsign",
                    ),
                ),
            ],
        ),
    ]
